@startuml
skinparam roundCorner 10
skinparam shadowing false
skinparam classFontName Lato
skinparam classFontSize 16
skinparam defaultFontName Source Code Pro
skinparam defaultFontSize 14
skinparam ClassAttributeFontStyle normal
skinparam ClassBackgroundColor white
skinparam ClassBorderColor black
skinparam ClassBorderThickness 1
skinparam ArrowColor black
skinparam linetype polyline

class dev.nymann.presentation.Client {
~ Scanner scanner
~ ISensorService sensorService
- void printWelcome()
- void printPrompt()
- ICommand getCommandFromUserInput()
- String getCommandResponseOrErrorMessage(ICommand)
- String executeCommandOrDisplayHelp(ICommand)
- void printMessage(String)
- void printMessage(String,boolean)
- String readInput()
- String help()
}
@enduml